// Generated by CoffeeScript 1.6.2
(function() {
  var NodeHttpService, e;

  NodeHttpService = {
    oembedRequest: function(url, callback_ok, callback_error) {
      var request;

      request = require("request");
      return request(url, function(error, response, body) {
        var json;

        if (error) {
          return callback_error(error);
        } else {
          json = JSON.parse(body);
          return callback_ok(json);
        }
      });
    }
  };

  try {
    exports.NodeHttpService = NodeHttpService;
  } catch (_error) {
    e = _error;
    null;
  }

}).call(this);
