// Generated by CoffeeScript 1.6.2
(function() {
  var MediaParserUtils;

  MediaParserUtils = {
    format: function() {
      var i, reg, s, _i, _ref;

      s = arguments[0];
      for (i = _i = 0, _ref = arguments.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        reg = new RegExp("\\{" + i + "\\}", "gm");
        s = s.replace(reg, arguments[i + 1]);
      }
      return s;
    },
    getBestSize: function(sizes, size_width) {
      var key, pair, sizes_sorted, value, _i, _len;

      sizes_sorted = [];
      for (key in sizes) {
        value = sizes[key];
        sizes_sorted.push([key, value]);
      }
      sizes_sorted = sizes_sorted.sort(function(a, b) {
        return a[1] - b[1];
      });
      for (_i = 0, _len = sizes_sorted.length; _i < _len; _i++) {
        pair = sizes_sorted[_i];
        key = pair[0];
        value = pair[1];
        if (value >= size_width) {
          return key;
        }
      }
      return key;
    }
  };

}).call(this);
